version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hrms_postgres
    environment:
      POSTGRES_DB: hrms
      POSTGRES_USER: batman
      POSTGRES_PASSWORD: Ilyosbek0925
    ports:
      - "5432:5432"
    volumes:
      - hrms_postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: hrms_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hrms
      SPRING_DATASOURCE_USERNAME: batman
      SPRING_DATASOURCE_PASSWORD: Ilyosbek0925
    ports:
      - "8080:8080"

volumes:
  hrms_postgres_data:
    external: true
