
services:
  app:
    build: . # Dockerfile shu papkada bo‘lishi kerak
    container_name: myproject1
    ports:
      - "8080:8080" # Tashqi port -> Konteyner port
    depends_on:
      - postgres # Dasturdan oldin postgres ishga tushadi
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hrms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ilyosbek0925

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: hrms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ilyosbek0925
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Ma'lumotlar saqlanadigan joy

volumes:
  pgdata:
